#' \code{mult_phase_type} class
#'
#' Description of the class \code{mult_phase_type}, which represents the multivariate phase-type
#' distribution.
#'
#' \code{cont_phase_type} is the generator function for the multivariate phase-type distribution class
#' of the same name, which inherits from \code{list}. The class is generated by supplying a sub-intensity
#' matrix, an optional initial probability vector and a reward matrix. If the initial probabilities are not specified,
#' then they are automatically generated as the first state having a probability of 1 and the rest
#' a probability of 0.
#'
#' @param subint_mat matrix
#' @param init_probs vector, a one-row matrix or \code{NULL}.
#' @param reward_mat matrix
#'
#' @usage mult_phase_type(subint_mat = NULL, reward_mat = NULL, init_probs = NULL)
#'
#' @example
#'
#' subint_mat = matrix(c(-3, 0, 0, 2, -2, 0, 0, 1, -1), nrow = 3, ncol = 3)
#' reward_mat = matrix(sample(seq(0, 10), 6), nrow = 3, ncol = 2)
#' mult_phase_type(subint_mat, reward_mat)
#'
#' @export

mult_phase_type <- function(subint_mat = NULL, reward_mat = NULL, init_probs = NULL) {
  if (is.null(subint_mat)) {
    stop('Unable to construct the phase-type distribution. Please provide a valid subintensity matrix.')
  } else if (is.matrix(subint_mat)) {
    if (is.null(init_probs)) {
      init_probs <- matrix(c(1, rep(0, nrow(subint_mat) - 1)), 1, nrow(subint_mat))
      warning('The initial probability vector is automatically generated.')
    } else if (sum(rowSums(subint_mat) > 0) != 0) {
      stop('The rowsums in subintensity matrix have to be non-positive')
    } else if ((is.vector(init_probs) & is.atomic(init_probs)) | is.matrix(init_probs)) {
      if (nrow(subint_mat) == length(init_probs)) {
        init_probs <- matrix(init_probs, nrow = 1)
      } else {
        stop('The length of the initial probabilities does not match the size of the subintensity matrix.')
      }
    } else {
      stop('The initial probabilities must be a a matrix with one row or a vector.')
    }
  } else {
    stop('The subintensity matrix must be a matrix.')
  }

  if (is.null(reward_mat)) {
    stop('Unable to construct the phase-type distribution. Please provide a valid reward matrix.')
  } else if (is.matrix(reward_mat)){
    if (nrow(reward_mat) != nrow(subint_mat)) {
      stop('The number of rows in the reward matrix does not match the number of rows in the subintensity matrix.')
    }
  } else {
    stop('The reward matrix must be a matrix.')
  }


  value <- list(subint_mat = subint_mat,
                init_probs = init_probs,
                defect = 1-sum(init_probs),
                reward_mat = reward_mat)
  attr(value, "class") <- "mult_phase_type"
  value
}






